url: http://joshmccall221.github.io
#baseurl: /
#baseurl: /agency-jekyll-theme/

# Site settings
title: First Church of the Open Bible 
email: joshmccall221@gmail.com
description: "Writee  aan awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mark Hornback 
  pic: 1
  position: Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Bill Hornback 
  pic: 2
  position: Lead Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
