url: https://ascendpotential.ca
repository: heatheranderson/heatheranderson.github.io

# Site settings
title: Ascend Potential
email: heather@ascendpotential.ca
description: "Executive coaching and life coaching services by Heather Anderson, Certified Integral Master Coach(tm). Reach your goals not your limits."

# Heather collections
collections:
  offerings:
    output: false
  testimonials:
    output: false
  about:
    output: false
  coaching:
    output: false

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ascendpotential
  - title: facebook
    url:
  - title: instagram
    url: https://www.instagram.com/ascendpotential/
  - title: linkedin
    url: https://www.linkedin.com/in/heathernoelleanderson/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
