url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Psychotherapy - Grateful mood
email: your-email@domain.com
description: "Online psychotherapy and counseling - video, chat or e-mail."


# Team names, titles and social links
people:
- name: Dr. Raluca Duta
  pic: 1
  position: therapist & counsler
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 10000 Prague 10
  - line: Czech Republic, 100 00

# Build settings
markdown: kramdown
permalink: pretty
