url: https://et.ethz.ch
baseurl: /

# Site settings
title: E.Tutorials
email: et@ethz.ch
description: "Online Learning materials for schools and universities. Developed and maintained at the ETH Zurich"
languages: ["de", "en", "es"]
exclude_from_localizations: ["js", "img", "css"]


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 009BF0
  secondary: 007CC0
  secondary-dark: 231f20

collections:
  courses:
    output: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: etutorial

#
# !! You don't need to change any of the configuration flags below !!
#

highlighter: pygments

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/orgs/Educational-Engineering

# Postal address (add as many lines as necessary)
address:
  - line: ETH Z체rich
  - line: Department Informatik
  - line:
  - line: <strong>Dr. Lukas F채ssler</strong>
  - line: Informationstechnologie und Ausbildung
  - line: CAB F 13.1
  - line: Universit채tstrasse 6
  - line:
  - line: 8092 Z체rich
  - line: Switzerland

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
