url: https://Olifee.github.io
baseurl: /Olifee.github.io/

# Site settings
title: Vanessa Ackermann
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin 
    url: http://linkedin.com/in/vanessa-ackermann
  - title: xing
    url: https://www.xing.com/profile/Vanessa_Ackermann7
  - title: github
    url: http://github.com/Olifee
  

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
