url: "https://brotherhood.ink"
baseurl:  ""

# Site settings
title: Brotherhood Saloon Tattoo Studio in Velbert
email: kingovi@gmail.com
description: "Brotherhood Saloon Tattoo Studio in Velbert. Tattoo, Piercing.


# Team names, titles and social links
people:
- name: Alex
  pic: 1
  position: Founder & Owner
  social:
    - title: instagram
      url: http://instagram.com

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
